name: My first workflow

on: [push]

jobs:
  first_job:
     runs-on: ubuntu-latest
     steps:
     - name: Welcome message
       run: echo "My first Github ACtion Job"
     - name: List Files
       run: ls 
     - name: Files PATH
       run: pwd
     - name: Read Files
       run: cat README.md 

